### ISSUE TITLE
Setting Search Engine?

### ISSUE THREAD

**Issue by kieransaul** [areking/Minimal-startpage#1]
Hi,
I'm trying to set the search engine, but I'm unsure how to? When I press enter to the search bar it just takes me to the same page again. [Imgur](https://i.imgur.com/eaCbLPn.png)

Thanks!

**Comment by areking** [comment]
yes, sorry for that. i didn't notice i forgot to add just a line with the var 'defaultSearch' that corrisponds to google.
now it works.
